services:
  gh_runner:
    build:
      context: ../code/dockerised-runners/ubuntu
      dockerfile: Dockerfile
    image: ubuntu-gh-runner:0.0.0
    env_file: ./gh-runner/.env
    restart: always
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
